name: kalman_net
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.20.1
  - scipy=1.8.1
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - pytorch=1.10.1
  - pip
  - pip:
      - pyParticleEst==1.1.4